ALTER TABLE users ADD COLUMN IF NOT EXISTS email_verified BOOL DEFAULT false;
ALTER TABLE users ADD COLUMN IF NOT EXISTS verification_token STRING;
ALTER TABLE users ADD COLUMN IF NOT EXISTS verification_token_expires TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN IF NOT EXISTS reset_token STRING;
ALTER TABLE users ADD COLUMN IF NOT EXISTS reset_token_expires TIMESTAMPTZ;
